[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "lightlike"
readme = { "file" = "README.md", "content-type" = "text/markdown" }
license = { file = "LICENSE" }
requires-python = ">=3.14"
dynamic = ["version"]
dependencies = [
    # Dependencies with conditional "platform_system != 'Android'" fail to build on termux.
    "Pygments>=2.17.2",
    "SQLAlchemy==2.0.31",
    "apscheduler>=3.11.3",
    "cachetools>=5.3.3",
    "click==8.1.7",
    "cryptography>=42.0.7",
    "dateparser==1.2.0",
    "fasteners==0.19",
    "fuzzyfinder>=2.2.0",
    "google-cloud-bigquery-storage>=2.26.0; platform_system != 'Android'",
    "google-cloud-bigquery>=3.18.0",
    "greenlet>=3.0.3",
    "httpx>=0.27.0",
    "more-itertools>=10.2.0",
    "packaging>=23.2",
    "prompt-toolkit~=3.0.47",
    "pywin32-ctypes>=0.2.2; sys_platform == 'win32'",
    "pywin32>=306; sys_platform == 'win32'",
    "questionary @ git+https://github.com/tmbo/questionary@caad2e5ce3694d53d1a0666751339262799bed9f",
    "rich~=13.7.1",
    "rsa>=4.9",
    "rtoml>=0.13.0",
    "sniffio>=1.3.1",
    "sqlalchemy-bigquery~=1.11.0",
    "tzlocal>=4",
]

[project.urls]
Repository = "https://github.com/ayvi-0001/lightlike-cli"

[project.scripts]
lightlike = "lightlike.cli:main"

[project.optional-dependencies]
dev = [
    "pytest-order==1.2.1",
    "pytest-xdist==3.6.1",
    "pytest==8.2.2",
    "ruff>=0.16.6",
    "ty>=0.0.84",
    "types-Pygments>=2.17.0.0",
    "types-dateparser>=1.1.4.20240106",
    "types-six>=1.16.21.20240513",
]
pandas = [
    "db-dtypes>=1.2.0; platform_system != 'Android'",
    "pandas>=2.2.1; platform_system != 'Android'",
]
all = ["lightlike[dev, pandas]"]

[tool.hatch.build.targets.wheel]
packages = ["lightlike"]
dependencies = ["click", "rich"]

[tool.hatch.build.targets.sdist]
packages = ["lightlike"]
dependencies = ["click", "rich"]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
format-jinja = """
    {%- if distance == 0 -%}
        {{ serialize_pep440(base, stage, revision, metadata=[] if not dirty else ['dirty']) }}
    {%- elif revision is not none -%}
        {{ serialize_pep440(base, stage, revision + 1, dev=distance, metadata=[commit] if not dirty else [commit, 'dirty']) }}
    {%- else -%}
        {{ serialize_pep440(bump_version(base), stage, revision, dev=distance, metadata=[commit] if not dirty else [commit, 'dirty']) }}
    {%- endif -%}
"""

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
preview = true
exclude = [".venv"]
fix = true
line-length = 99
src = ["lightlike", "tests"]
unsafe-fixes = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
extend-ignore = [
    "blank-line-before-class",
    "docstring-missing-exception",
    "docstring-missing-returns",
    "import-outside-top-level",
    "incorrect-blank-line-before-class",
    "line-contains-fixme",
    "line-contains-hack",
    "line-contains-todo",
    "line-contains-xxx",
    "missing-copyright-notice",
    "missing-todo-link",
    "multi-line-summary-first-line",
    "too-many-arguments",
    "too-many-positional-arguments",
    "undocumented-magic-method",
    "undocumented-public-class",
    "undocumented-public-function",
    "undocumented-public-init",
    "undocumented-public-method",
    "undocumented-public-module",
    "undocumented-public-package",
    "unused-async",
    "unused-variable",
]
extend-fixable = [
    "COM", # flake8-commas
    "E",   # pycodestyle / error
    "I",   # isort
    "PYI", # flake8-pyi
    "RSE", # flake8-raise
    "RUF", # ruff-specific rules
    "TC",  # flake8-type-checking
    "UP",  # pyupgrade
    "W",   # pycodestyle / warning
]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
preview = true
