# mypy: disable-error-code="import-untyped"
import re
from typing import Sequence

from pygments.lexer import RegexLexer, words
from pygments.token import (
    Comment,
    Keyword,
    Name,
    Number,
    Operator,
    Punctuation,
    String,
    Whitespace,
)

__all__: Sequence[str] = ("BqSqlLexer",)


class BqSqlLexer(RegexLexer):
    name = "SQL"
    aliases = ["sql"]
    filenames = ["*.sql"]
    mimetypes = ["text/x-sql"]

    flags = re.IGNORECASE
    tokens = {
        "root": [
            (r"\s+", Whitespace),
            (r"--.*\n?", Comment.Single),
            (r"/\*", Comment.Multiline, "multiline-comments"),
            (
                words(
                    (
                        "ABS",
                        "ACOS",
                        "ACOSH",
                        "ADD",
                        "ADD REPLICA",
                        "ALL",
                        "ALTER",
                        "AND",
                        "ANY",
                        "ANY_VALUE",
                        "APPROX_COUNT_DISTINCT",
                        "APPROX_QUANTILES",
                        "APPROX_TOP_COUNT",
                        "APPROX_TOP_SUM",
                        "ARRAY",
                        "ARRAY_AGG",
                        "ARRAY_CONCAT",
                        "ARRAY_CONCAT_AGG",
                        "ARRAY_LENGTH",
                        "ARRAY_REVERSE",
                        "ARRAY_TO_STRING",
                        "AS",
                        "ASC",
                        "ASCII",
                        "ASIN",
                        "ASINH",
                        "ASSERT_ROWS_MODIFIED",
                        "ASSIGNMENT",
                        "ASSIGNMENTS_BY_PROJECT",
                        "ASSIGNMENT_CHANGES_BY_PROJECT",
                        "AT",
                        "ATAN",
                        "ATAN2",
                        "ATANH",
                        "AVG",
                        "BEGIN",
                        "BEGIN TRANSACTION",
                        "BETWEEN",
                        "BIT_AND",
                        "BIT_COUNT",
                        "BIT_OR",
                        "BIT_XOR",
                        "BI_CAPACITIES",
                        "BI_CAPACITY SET OPTIONS",
                        "BI_CAPACITY_CHANGES",
                        "BOOL",
                        "BREAK",
                        "BY",
                        "BYTE_LENGTH",
                        "CALL",
                        "CAPACITY",
                        "CAPACITY SET OPTIONS",
                        "CAPACITY_COMMITMENTS_BY_PROJECT",
                        "CAPACITY_COMMITMENT_CHANGES_BY_PROJECT",
                        "CASE",
                        "CAST",
                        "CBRT",
                        "CEIL",
                        "CEILING",
                        "CHARACTER_LENGTH",
                        "CHAR_LENGTH",
                        "CHR",
                        "CLONE",
                        "CODE_POINTS_TO_BYTES",
                        "CODE_POINTS_TO_STRING",
                        "COLLATE",
                        "COLUMN",
                        "COLUMNS",
                        "COLUMN_FIELD_PATHS",
                        "COMMIT TRANSACTION",
                        "CONCAT",
                        "CONSTRAINT",
                        "CONSTRAINT_COLUMN_USAGE",
                        "CONTAINS",
                        "CONTAINS_SUBSTR",
                        "CONTINUE",
                        "COPY",
                        "CORR",
                        "COS",
                        "COSH",
                        "COSINE_DISTANCE",
                        "COT",
                        "COTH",
                        "COUNT",
                        "COUNTIF",
                        "COVAR_POP",
                        "COVAR_SAMP",
                        "CREATE",
                        "CROSS",
                        "CSC",
                        "CSCH",
                        "CUBE",
                        "CUME_DIST",
                        "CURRENT",
                        "CURRENT_DATE",
                        "CURRENT_DATETIME",
                        "CURRENT_TIME",
                        "CURRENT_TIMESTAMP",
                        "DATA TYPE",
                        "DATE",
                        "DATETIME",
                        "DATETIME_ADD",
                        "DATETIME_DIFF",
                        "DATETIME_SUB",
                        "DATETIME_TRUNC",
                        "DATE_ADD",
                        "DATE_DIFF",
                        "DATE_FROM_UNIX_DATE",
                        "DATE_SUB",
                        "DATE_TRUNC",
                        "DECLARE",
                        "DEFAULT",
                        "DEFAULT COLLATE",
                        "DEFINE",
                        "DELETE",
                        "DENSE_RANK",
                        "DESC",
                        "DISTINCT",
                        "DIV",
                        "DROP",
                        "DROP REPLICA",
                        "EDIT_DISTANCE",
                        "EFFECTIVE_PROJECT_OPTIONS",
                        "ELSE",
                        "END",
                        "ENDS_WITH",
                        "ENUM",
                        "ERROR",
                        "ESCAPE",
                        "EUCLIDEAN_DISTANCE",
                        "EXCEPT",
                        "EXCEPTION",
                        "EXCLUDE",
                        "EXECUTE IMMEDIATE",
                        "EXISTS",
                        "EXP",
                        "EXTERNAL TABLE",
                        "EXTRACT",
                        "FALSE",
                        "FARM_FINGERPRINT",
                        "FETCH",
                        "FIRST_VALUE",
                        "FLOAT64",
                        "FLOOR",
                        "FOLLOWING",
                        "FOR",
                        "FOREIGN KEY",
                        "FORMAT",
                        "FORMAT_DATE",
                        "FORMAT_DATETIME",
                        "FORMAT_TIME",
                        "FROM",
                        "FROM_BASE32",
                        "FROM_BASE64",
                        "FROM_HEX",
                        "FULL",
                        "FUNCTION",
                        "GENERATE_ARRAY",
                        "GENERATE_DATE_ARRAY",
                        "GENERATE_TIMESTAMP_ARRAY",
                        "GRANT",
                        "GREATEST",
                        "GROUP",
                        "GROUPING",
                        "GROUPS",
                        "HASH",
                        "HAVING",
                        "IEEE_DIVIDE",
                        "IF",
                        "IF EXISTS",
                        "IF NOT EXISTS",
                        "IGNORE",
                        "IN",
                        "INFORMATION_SCHEMA",
                        "INITCAP",
                        "INNER",
                        "INSERT",
                        "INSTR",
                        "INT64",
                        "INTERSECT",
                        "INTERVAL",
                        "INTO",
                        "IS",
                        "IS_INF",
                        "IS_NAN",
                        "ITERATE",
                        "JOBS_BY_FOLDER",
                        "JOBS_BY_ORGANIZATION",
                        "JOBS_BY_PROJECT",
                        "JOBS_BY_USER",
                        "JOBS_TIMELINE_BY_FOLDER",
                        "JOBS_TIMELINE_BY_ORGANIZATION",
                        "JOBS_TIMELINE_BY_PROJECT",
                        "JOBS_TIMELINE_BY_USER",
                        "JOIN",
                        "JSON_ARRAY",
                        "JSON_ARRAY_APPEND",
                        "JSON_ARRAY_INSERT",
                        "JSON_EXTRACT",
                        "JSON_EXTRACT_ARRAY",
                        "JSON_EXTRACT_SCALAR",
                        "JSON_EXTRACT_STRING_ARRAY",
                        "JSON_OBJECT",
                        "JSON_QUERY",
                        "JSON_QUERY_ARRAY",
                        "JSON_REMOVE",
                        "JSON_SET",
                        "JSON_STRIP_NULLS",
                        "JSON_STRIP_NoneS",
                        "JSON_TYPE",
                        "JSON_VALUE",
                        "JSON_VALUE_ARRAY",
                        "JUSTIFY_DAYS",
                        "JUSTIFY_HOURS",
                        "JUSTIFY_INTERVAL",
                        "KEY_COLUMN_USAGE",
                        "LAG",
                        "LAST_DAY",
                        "LAST_VALUE",
                        "LATERAL",
                        "LAX_BOOL",
                        "LAX_FLOAT64",
                        "LAX_INT64",
                        "LAX_STRING",
                        "LEAD",
                        "LEAST",
                        "LEAVE",
                        "LEFT",
                        "LENGTH",
                        "LIKE",
                        "LIMIT",
                        "LN",
                        "LOG",
                        "LOG10",
                        "LOGICAL_AND",
                        "LOGICAL_OR",
                        "LOOKUP",
                        "LOOP",
                        "LOWER",
                        "LPAD",
                        "LTRIM",
                        "MAKE_INTERVAL",
                        "MATERIALIZED VIEW",
                        "MATERIALIZED VIEW SET OPTIONS",
                        "MATERIALIZED_VIEWS",
                        "MAX",
                        "MAX_BY",
                        "MD5",
                        "MERGE",
                        "MIN",
                        "MIN_BY",
                        "MOD",
                        "NATURAL",
                        "NEW",
                        "NO",
                        "NORMALIZE",
                        "NORMALIZE_AND_CASEFOLD",
                        "NOT",
                        "NOT None",
                        "NTH_VALUE",
                        "NTILE",
                        "None",
                        "NoneS",
                        "OCTET_LENGTH",
                        "OF",
                        "ON",
                        "OPTIONS",
                        "OR",
                        "ORDER",
                        "ORGANIZATION SET OPTIONS",
                        "ORGANIZATION_OPTIONS",
                        "ORGANIZATION_OPTIONS_CHANGES",
                        "OUTER",
                        "OVER",
                        "PARAMETERS",
                        "PARSE_BIGNUMERIC",
                        "PARSE_DATE",
                        "PARSE_DATETIME",
                        "PARSE_JSON",
                        "PARSE_NUMERIC",
                        "PARSE_TIME",
                        "PARTITION",
                        "PARTITIONS",
                        "PERCENTILE_CONT",
                        "PERCENTILE_DISC",
                        "PERCENT_RANK",
                        "POW",
                        "POWER",
                        "PRECEDING",
                        "PRIMARY KEY",
                        "PROCEDING",
                        "PROCEDURE",
                        "PROJECT SET OPTIONS",
                        "PROJECT_OPTIONS",
                        "PROJECT_OPTIONS_CHANGES",
                        "PROTO",
                        "QUALIFY",
                        "RAISE",
                        "RAND",
                        "RANGE",
                        "RANGE_BUCKET",
                        "RANK",
                        "RECURSIVE",
                        "REGEXP_CONTAINS",
                        "REGEXP_EXTRACT",
                        "REGEXP_EXTRACT_ALL",
                        "REGEXP_INSTR",
                        "REGEXP_REPLACE",
                        "REGEXP_SUBSTR",
                        "RENAME",
                        "REPEAT",
                        "REPLACE",
                        "REPLACE EXTERNAL TABLE",
                        "REPLACE FUNCTION",
                        "REPLACE MATERIALIZED VIEW",
                        "REPLACE PROCEDURE",
                        "REPLACE SCHEMA",
                        "REPLACE TABLE",
                        "REPLACE VIEW",
                        "RESERVATION",
                        "RESERVATIONS_BY_PROJECT",
                        "RESERVATIONS_TIMELINE_BY_PROJECT",
                        "RESERVATION_CHANGES_BY_PROJECT",
                        "RESPECT",
                        "RETURN",
                        "REVERSE",
                        "REVOKE",
                        "RIGHT",
                        "ROLLBACK",
                        "ROLLBACK TRANSACTION",
                        "ROLLUP",
                        "ROUND",
                        "ROUTINES",
                        "ROUTINE_OPTIONS",
                        "ROW ACCESS POLICY",
                        "ROWS",
                        "ROW_NUMBER",
                        "RPAD",
                        "RTRIM",
                        "SAFE_ADD",
                        "SAFE_CAST",
                        "SAFE_CONVERT_BYTES_TO_STRING",
                        "SAFE_DIVIDE",
                        "SAFE_MULTIPLY",
                        "SAFE_NEGATE",
                        "SAFE_SUBTRACT",
                        "SCHEMA",
                        "SCHEMATA",
                        "SCHEMATA_LINKS",
                        "SCHEMATA_OPTIONS",
                        "SEARCH INDEX",
                        "SEARCH_INDEXES",
                        "SEARCH_INDEX_COLUMNS",
                        "SEC",
                        "SECH",
                        "SELECT",
                        "SESSIONS_BY_PROJECT",
                        "SESSIONS_BY_USER",
                        "SET",
                        "SHA1",
                        "SHA256",
                        "SHA512",
                        "SHARED_DATASET_USAGE",
                        "SIGN",
                        "SIN",
                        "SINH",
                        "SNAPSHOT TABLE",
                        "SOME",
                        "SOUNDEX",
                        "SPLIT",
                        "SQRT",
                        "STARTS_WITH",
                        "STDDEV",
                        "STDDEV_POP",
                        "STDDEV_SAMP",
                        "STREAMING_TIMELINE_BY_FOLDER",
                        "STREAMING_TIMELINE_BY_ORGANIZATION",
                        "STREAMING_TIMELINE_BY_PROJECT",
                        "STRING",
                        "STRING_AGG",
                        "STRPOS",
                        "STRUCT",
                        "SUBSTR",
                        "SUBSTRING",
                        "SUM",
                        "TABLE",
                        "TABLE FUNCTION",
                        "TABLES",
                        "TABLESAMPLE",
                        "TABLE_CONSTRAINTS",
                        "TABLE_OPTIONS",
                        "TABLE_SNAPSHOTS",
                        "TABLE_STORAGE_BY_ORGANIZATION",
                        "TABLE_STORAGE_BY_PROJECT",
                        "TABLE_STORAGE_USAGE_TIMELINE",
                        "TABLE_STORAGE_USAGE_TIMELINE_BY_ORGANIZATION",
                        "TAN",
                        "TANH",
                        "THEN",
                        "TIME",
                        "TIME_ADD",
                        "TIME_DIFF",
                        "TIME_SUB",
                        "TIME_TRUNC",
                        "TO",
                        "TO_BASE32",
                        "TO_BASE64",
                        "TO_CODE_POINTS",
                        "TO_HEX",
                        "TO_JSON",
                        "TO_JSON_STRING",
                        "TRANSLATE",
                        "TREAT",
                        "TRIM",
                        "TRUE",
                        "TRUNC",
                        "TRUNCATE",
                        "UNBOUNDED",
                        "UNICODE",
                        "UNION",
                        "UNIX_DATE",
                        "UNNEST",
                        "UPDATE",
                        "UPPER",
                        "USING",
                        "VALUES",
                        "VARIANCE",
                        "VAR_POP",
                        "VAR_SAMP",
                        "VECTOR_INDEXES",
                        "VECTOR_INDEX_COLUMNS",
                        "VECTOR_INDEX_OPTIONS",
                        "VIEW",
                        "VIEW SET OPTIONS",
                        "WHEN",
                        "WHEN ERROR",
                        "WHERE",
                        "WHILE",
                        "WINDOW",
                        "WITH",
                        "WITHIN",
                        "__TABLES__",
                    ),
                    suffix=r"\b",
                ),
                Keyword,
            ),
            (
                words(
                    (
                        "ARRAY",
                        "BIGINT",
                        "BINARY",
                        "BIT",
                        "BLOB",
                        "BOOLEAN",
                        "CHAR",
                        "CHARACTER",
                        "DATE",
                        "DEC",
                        "DECIMAL",
                        "FLOAT",
                        "INT",
                        "INT8",
                        "INTEGER",
                        "INTERVAL",
                        "NUMBER",
                        "NUMERIC",
                        "REAL",
                        "SERIAL",
                        "SERIAL8",
                        "SMALLINT",
                        "TEXT",
                        "VARCHAR",
                        "VARYING",
                    ),
                    suffix=r"\b",
                ),
                Name.Builtin,
            ),
            (r"[+*/<>=~!@#%^&|`?-]", Operator),
            (r"[0-9]+", Number.Integer),
            (r"'(''|[^'])*'", String.Single),
            (r'"(""|[^"])*"', String.Symbol),
            (r"[a-z_][\w$]*", Name),
            (r"[;:()\[\],.]", Punctuation),
        ],
        "multiline-comments": [
            (r"/\*", Comment.Multiline, "multiline-comments"),
            (r"\*/", Comment.Multiline, "#pop"),
            (r"[^/*]+", Comment.Multiline),
            (r"[/*]", Comment.Multiline),
        ],
    }

    def analyse_text(self, text: str) -> None:
        return

    @staticmethod
    def lower() -> str:
        return "bqsqllexer"
