from typing import Any, Sequence

__all__: Sequence[str] = ("SQL_KEYWORDS", "KEYWORD_META")


SQL_KEYWORDS: dict[str, Any] = {
    "CREATE": {
        "TABLE": {"LIKE": None, "IF NOT EXISTS": None},
        "VIEW": {"IF NOT EXISTS": None},
        "SCHEMA": {"IF NOT EXISTS": None},
        "OR": {
            "REPLACE SCHEMA": {},
            "REPLACE TABLE": {},
            "REPLACE VIEW": {},
            "REPLACE MATERIALIZED VIEW": {},
            "REPLACE EXTERNAL TABLE": {},
            "REPLACE FUNCTION": {},
            "REPLACE PROCEDURE": {},
        },
        "SNAPSHOT TABLE": {},
        "MATERIALIZED VIEW": {"IF NOT EXISTS": None},
        "FUNCTION": {"IF NOT EXISTS": None},
        "TABLE FUNCTION": {"IF NOT EXISTS": None},
        "PROCEDURE": {"IF NOT EXISTS": None},
        "EXTERNAL TABLE": {"IF NOT EXISTS": None},
        "CAPACITY": None,
        "RESERVATION": None,
        "ASSIGNMENT": None,
        "SEARCH INDEX": None,
        "ROW ACCESS POLICY": None,
    },
    "DROP": {
        "TABLE": {"IF EXISTS": None},
        "VIEW": {"IF EXISTS": None},
        "SCHEMA": {"IF EXISTS": None},
        "MATERIALIZED VIEW": {"IF EXISTS": None},
        "FUNCTION": {"IF EXISTS": None},
        "TABLE FUNCTION": {"IF EXISTS": None},
        "PROCEDURE": {"IF EXISTS": None},
        "EXTERNAL TABLE": {"IF EXISTS": None},
        "CAPACITY": None,
        "RESERVATION": None,
        "ASSIGNMENT": None,
        "SEARCH INDEX": None,
        "ROW ACCESS POLICY": None,
    },
    "ALTER": {
        "VIEW SET OPTIONS": None,
        "MATERIALIZED VIEW SET OPTIONS": None,
        "ORGANIZATION SET OPTIONS": None,
        "PROJECT SET OPTIONS": None,
        "BI_CAPACITY SET OPTIONS": None,
        "CAPACITY SET OPTIONS": None,
        "SCHEMA": {
            "SET": {"DEFAULT COLLATE": None, "OPTIONS": None},
            "ADD REPLICA": None,
            "DROP REPLICA": None,
        },
        "COLUMN": {
            "SET": {"OPTIONS": None, "DATA TYPE": None, "DEFAULT": None},
            "DROP": {"NOT None": None, "DEFAULT": None},
        },
        "TABLE": {
            "SET": {"OPTIONS": None, "DEFAULT COLLATE": None},
            "ADD": {"COLUMN": None, "FOREIGN KEY": None, "PRIMARY KEY": None},
            "RENAME": {"TO": None, "COLUMN": None},
            "DROP": {"COLUMN": None, "PRIMARY KEY": None, "CONSTRAINT": None},
        },
    },
    "TRUNCATE": {"TABLE": None},
    "EXCEPTION": {"WHEN ERROR": None},
    "INFORMATION_SCHEMA": {
        "BI_CAPACITIES": None,
        "BI_CAPACITY_CHANGES": None,
        "EFFECTIVE_PROJECT_OPTIONS": None,
        "ORGANIZATION_OPTIONS": None,
        "ORGANIZATION_OPTIONS_CHANGES": None,
        "PROJECT_OPTIONS": None,
        "PROJECT_OPTIONS_CHANGES": None,
        "SCHEMATA": None,
        "SCHEMATA_LINKS": None,
        "SCHEMATA_OPTIONS": None,
        "SHARED_DATASET_USAGE": None,
        "JOBS_BY_PROJECT": None,
        "JOBS_BY_USER": None,
        "JOBS_BY_FOLDER": None,
        "JOBS_BY_ORGANIZATION": None,
        "JOBS_TIMELINE_BY_PROJECT": None,
        "JOBS_TIMELINE_BY_USER": None,
        "JOBS_TIMELINE_BY_FOLDER": None,
        "JOBS_TIMELINE_BY_ORGANIZATION": None,
        "ASSIGNMENTS_BY_PROJECT": None,
        "ASSIGNMENT_CHANGES_BY_PROJECT": None,
        "CAPACITY_COMMITMENTS_BY_PROJECT": None,
        "CAPACITY_COMMITMENT_CHANGES_BY_PROJECT": None,
        "RESERVATIONS_BY_PROJECT": None,
        "RESERVATION_CHANGES_BY_PROJECT": None,
        "RESERVATIONS_TIMELINE_BY_PROJECT": None,
        "PARAMETERS": None,
        "ROUTINES": None,
        "ROUTINE_OPTIONS": None,
        "SEARCH_INDEXES": None,
        "SEARCH_INDEX_COLUMNS": None,
        "SESSIONS_BY_PROJECT": None,
        "SESSIONS_BY_USER": None,
        "STREAMING_TIMELINE_BY_PROJECT": None,
        "STREAMING_TIMELINE_BY_FOLDER": None,
        "STREAMING_TIMELINE_BY_ORGANIZATION": None,
        "COLUMNS": None,
        "COLUMN_FIELD_PATHS": None,
        "CONSTRAINT_COLUMN_USAGE": None,
        "KEY_COLUMN_USAGE": None,
        "PARTITIONS": None,
        "TABLES": None,
        "TABLE_OPTIONS": None,
        "TABLE_CONSTRAINTS": None,
        "TABLE_SNAPSHOTS": None,
        "TABLE_STORAGE_BY_PROJECT": None,
        "TABLE_STORAGE_BY_ORGANIZATION": None,
        "TABLE_STORAGE_USAGE_TIMELINE": None,
        "TABLE_STORAGE_USAGE_TIMELINE_BY_ORGANIZATION": None,
        "VECTOR_INDEXES": None,
        "VECTOR_INDEX_COLUMNS": None,
        "VECTOR_INDEX_OPTIONS": None,
        "MATERIALIZED_VIEWS": None,
    },
    "ABS": None,
    "ACOS": None,
    "ACOSH": None,
    "ADD": None,
    "ADD REPLICA": None,
    "ALL": None,
    "AND": None,
    "ANY": None,
    "ANY_VALUE": None,
    "APPROX_COUNT_DISTINCT": None,
    "APPROX_QUANTILES": None,
    "APPROX_TOP_COUNT": None,
    "APPROX_TOP_SUM": None,
    "ARRAY": None,
    "ARRAY_AGG": None,
    "ARRAY_CONCAT": None,
    "ARRAY_CONCAT_AGG": None,
    "ARRAY_LENGTH": None,
    "ARRAY_REVERSE": None,
    "ARRAY_TO_STRING": None,
    "AS": None,
    "ASC": None,
    "ASCII": None,
    "ASIN": None,
    "ASINH": None,
    "ASSERT_ROWS_MODIFIED": None,
    "ASSIGNMENT": None,
    "ASSIGNMENTS_BY_PROJECT": None,
    "ASSIGNMENT_CHANGES_BY_PROJECT": None,
    "AT": None,
    "ATAN": None,
    "ATAN2": None,
    "ATANH": None,
    "AVG": None,
    "BEGIN": None,
    "BEGIN TRANSACTION": None,
    "BETWEEN": None,
    "BIT_AND": None,
    "BIT_COUNT": None,
    "BIT_OR": None,
    "BIT_XOR": None,
    "BI_CAPACITIES": None,
    "BI_CAPACITY SET OPTIONS": None,
    "BI_CAPACITY_CHANGES": None,
    "BOOL": None,
    "BREAK": None,
    "BY": None,
    "BYTE_LENGTH": None,
    "CALL": None,
    "CAPACITY": None,
    "CAPACITY SET OPTIONS": None,
    "CAPACITY_COMMITMENTS_BY_PROJECT": None,
    "CAPACITY_COMMITMENT_CHANGES_BY_PROJECT": None,
    "CASE": None,
    "CAST": None,
    "CBRT": None,
    "CEIL": None,
    "CEILING": None,
    "CHARACTER_LENGTH": None,
    "CHAR_LENGTH": None,
    "CHR": None,
    "CLONE": None,
    "CODE_POINTS_TO_BYTES": None,
    "CODE_POINTS_TO_STRING": None,
    "COLLATE": None,
    "COLUMN": None,
    "COLUMNS": None,
    "COLUMN_FIELD_PATHS": None,
    "COMMIT TRANSACTION": None,
    "CONCAT": None,
    "CONSTRAINT": None,
    "CONSTRAINT_COLUMN_USAGE": None,
    "CONTAINS": None,
    "CONTAINS_SUBSTR": None,
    "CONTINUE": None,
    "COPY": None,
    "CORR": None,
    "COS": None,
    "COSH": None,
    "COSINE_DISTANCE": None,
    "COT": None,
    "COTH": None,
    "COUNT": None,
    "COUNTIF": None,
    "COVAR_POP": None,
    "COVAR_SAMP": None,
    "CROSS": None,
    "CSC": None,
    "CSCH": None,
    "CUBE": None,
    "CUME_DIST": None,
    "CURRENT": None,
    "CURRENT_DATE": None,
    "CURRENT_DATETIME": None,
    "CURRENT_TIME": None,
    "CURRENT_TIMESTAMP": None,
    "DATA TYPE": None,
    "DATE": None,
    "DATETIME": None,
    "DATETIME_ADD": None,
    "DATETIME_DIFF": None,
    "DATETIME_SUB": None,
    "DATETIME_TRUNC": None,
    "DATE_ADD": None,
    "DATE_DIFF": None,
    "DATE_FROM_UNIX_DATE": None,
    "DATE_SUB": None,
    "DATE_TRUNC": None,
    "DECLARE": None,
    "DEFAULT": None,
    "DEFAULT COLLATE": None,
    "DEFINE": None,
    "DELETE": None,
    "DENSE_RANK": None,
    "DESC": None,
    "DISTINCT": None,
    "DIV": None,
    "DROP REPLICA": None,
    "EDIT_DISTANCE": None,
    "EFFECTIVE_PROJECT_OPTIONS": None,
    "ELSE": None,
    "END": None,
    "ENDS_WITH": None,
    "ENUM": None,
    "ERROR": None,
    "ESCAPE": None,
    "EUCLIDEAN_DISTANCE": None,
    "EXCEPT": None,
    "EXCLUDE": None,
    "EXECUTE IMMEDIATE": None,
    "EXISTS": None,
    "EXP": None,
    "EXTERNAL TABLE": None,
    "EXTRACT": None,
    "FALSE": None,
    "FARM_FINGERPRINT": None,
    "FETCH": None,
    "FIRST_VALUE": None,
    "FLOAT64": None,
    "FLOOR": None,
    "FOLLOWING": None,
    "FOR": None,
    "FOREIGN KEY": None,
    "FORMAT": None,
    "FORMAT_DATE": None,
    "FORMAT_DATETIME": None,
    "FORMAT_TIME": None,
    "FROM": None,
    "FROM_BASE32": None,
    "FROM_BASE64": None,
    "FROM_HEX": None,
    "FULL": None,
    "FUNCTION": None,
    "GENERATE_ARRAY": None,
    "GENERATE_DATE_ARRAY": None,
    "GENERATE_TIMESTAMP_ARRAY": None,
    "GRANT": None,
    "GREATEST": None,
    "GROUP": None,
    "GROUPING": None,
    "GROUPS": None,
    "HASH": None,
    "HAVING": None,
    "IEEE_DIVIDE": None,
    "IF": None,
    "IF NOT EXISTS": None,
    "IGNORE": None,
    "IN": None,
    "INITCAP": None,
    "INNER": None,
    "INSERT": None,
    "INSTR": None,
    "INT64": None,
    "INTERSECT": None,
    "INTERVAL": None,
    "INTO": None,
    "IS": None,
    "IS_INF": None,
    "IS_NAN": None,
    "ITERATE": None,
    "JOBS_BY_FOLDER": None,
    "JOBS_BY_ORGANIZATION": None,
    "JOBS_BY_PROJECT": None,
    "JOBS_BY_USER": None,
    "JOBS_TIMELINE_BY_FOLDER": None,
    "JOBS_TIMELINE_BY_ORGANIZATION": None,
    "JOBS_TIMELINE_BY_PROJECT": None,
    "JOBS_TIMELINE_BY_USER": None,
    "JOIN": None,
    "JSON_ARRAY": None,
    "JSON_ARRAY_APPEND": None,
    "JSON_ARRAY_INSERT": None,
    "JSON_EXTRACT": None,
    "JSON_EXTRACT_ARRAY": None,
    "JSON_EXTRACT_SCALAR": None,
    "JSON_EXTRACT_STRING_ARRAY": None,
    "JSON_OBJECT": None,
    "JSON_QUERY": None,
    "JSON_QUERY_ARRAY": None,
    "JSON_REMOVE": None,
    "JSON_SET": None,
    "JSON_STRIP_NoneS": None,
    "JSON_TYPE": None,
    "JSON_VALUE": None,
    "JSON_VALUE_ARRAY": None,
    "JUSTIFY_DAYS": None,
    "JUSTIFY_HOURS": None,
    "JUSTIFY_INTERVAL": None,
    "KEY_COLUMN_USAGE": None,
    "LAG": None,
    "LAST_DAY": None,
    "LAST_VALUE": None,
    "LATERAL": None,
    "LAX_BOOL": None,
    "LAX_FLOAT64": None,
    "LAX_INT64": None,
    "LAX_STRING": None,
    "LEAD": None,
    "LEAST": None,
    "LEAVE": None,
    "LEFT": None,
    "LENGTH": None,
    "LIKE": None,
    "LIMIT": None,
    "LN": None,
    "LOG": None,
    "LOG10": None,
    "LOGICAL_AND": None,
    "LOGICAL_OR": None,
    "LOOKUP": None,
    "LOOP": None,
    "LOWER": None,
    "LPAD": None,
    "LTRIM": None,
    "MAKE_INTERVAL": None,
    "MATERIALIZED VIEW": None,
    "MATERIALIZED VIEW SET OPTIONS": None,
    "MATERIALIZED_VIEWS": None,
    "MAX": None,
    "MAX_BY": None,
    "MD5": None,
    "MERGE": None,
    "MIN": None,
    "MIN_BY": None,
    "MOD": None,
    "NATURAL": None,
    "NEW": None,
    "NO": None,
    "NORMALIZE": None,
    "NORMALIZE_AND_CASEFOLD": None,
    "NOT": None,
    "NOT None": None,
    "NTH_VALUE": None,
    "NTILE": None,
    "None": None,
    "NoneS": None,
    "OCTET_LENGTH": None,
    "OF": None,
    "ON": None,
    "OPTIONS": None,
    "OR": None,
    "ORDER": None,
    "ORGANIZATION SET OPTIONS": None,
    "ORGANIZATION_OPTIONS": None,
    "ORGANIZATION_OPTIONS_CHANGES": None,
    "OUTER": None,
    "OVER": None,
    "PARAMETERS": None,
    "PARSE_BIGNUMERIC": None,
    "PARSE_DATE": None,
    "PARSE_DATETIME": None,
    "PARSE_JSON": None,
    "PARSE_NUMERIC": None,
    "PARSE_TIME": None,
    "PARTITION": None,
    "PARTITIONS": None,
    "PERCENTILE_CONT": None,
    "PERCENTILE_DISC": None,
    "PERCENT_RANK": None,
    "POW": None,
    "POWER": None,
    "PRECEDING": None,
    "PRIMARY KEY": None,
    "PROCEDING": None,
    "PROCEDURE": None,
    "PROJECT SET OPTIONS": None,
    "PROJECT_OPTIONS": None,
    "PROJECT_OPTIONS_CHANGES": None,
    "PROTO": None,
    "QUALIFY": None,
    "RAISE": None,
    "RAND": None,
    "RANGE": None,
    "RANGE_BUCKET": None,
    "RANK": None,
    "RECURSIVE": None,
    "REGEXP_CONTAINS": None,
    "REGEXP_EXTRACT": None,
    "REGEXP_EXTRACT_ALL": None,
    "REGEXP_INSTR": None,
    "REGEXP_REPLACE": None,
    "REGEXP_SUBSTR": None,
    "RENAME": None,
    "REPEAT": None,
    "REPLACE": None,
    "REPLACE EXTERNAL TABLE": None,
    "REPLACE FUNCTION": None,
    "REPLACE MATERIALIZED VIEW": None,
    "REPLACE PROCEDURE": None,
    "REPLACE SCHEMA": None,
    "REPLACE TABLE": None,
    "REPLACE VIEW": None,
    "RESERVATION": None,
    "RESERVATIONS_BY_PROJECT": None,
    "RESERVATIONS_TIMELINE_BY_PROJECT": None,
    "RESERVATION_CHANGES_BY_PROJECT": None,
    "RESPECT": None,
    "RETURN": None,
    "REVERSE": None,
    "REVOKE": None,
    "RIGHT": None,
    "ROLLBACK": None,
    "ROLLBACK TRANSACTION": None,
    "ROLLUP": None,
    "ROUND": None,
    "ROUTINES": None,
    "ROUTINE_OPTIONS": None,
    "ROW ACCESS POLICY": None,
    "ROWS": None,
    "ROW_NUMBER": None,
    "RPAD": None,
    "RTRIM": None,
    "SAFE_ADD": None,
    "SAFE_CAST": None,
    "SAFE_CONVERT_BYTES_TO_STRING": None,
    "SAFE_DIVIDE": None,
    "SAFE_MULTIPLY": None,
    "SAFE_NEGATE": None,
    "SAFE_SUBTRACT": None,
    "SCHEMA": None,
    "SCHEMATA": None,
    "SCHEMATA_LINKS": None,
    "SCHEMATA_OPTIONS": None,
    "SEARCH INDEX": None,
    "SEARCH_INDEXES": None,
    "SEARCH_INDEX_COLUMNS": None,
    "SEC": None,
    "SECH": None,
    "SELECT": None,
    "SESSIONS_BY_PROJECT": None,
    "SESSIONS_BY_USER": None,
    "SET": None,
    "SHA1": None,
    "SHA256": None,
    "SHA512": None,
    "SHARED_DATASET_USAGE": None,
    "SIGN": None,
    "SIN": None,
    "SINH": None,
    "SNAPSHOT TABLE": None,
    "SOME": None,
    "SOUNDEX": None,
    "SPLIT": None,
    "SQRT": None,
    "STARTS_WITH": None,
    "STDDEV": None,
    "STDDEV_POP": None,
    "STDDEV_SAMP": None,
    "STREAMING_TIMELINE_BY_FOLDER": None,
    "STREAMING_TIMELINE_BY_ORGANIZATION": None,
    "STREAMING_TIMELINE_BY_PROJECT": None,
    "STRING": None,
    "STRING_AGG": None,
    "STRPOS": None,
    "STRUCT": None,
    "SUBSTR": None,
    "SUBSTRING": None,
    "SUM": None,
    "TABLE": None,
    "TABLE FUNCTION": None,
    "TABLES": None,
    "TABLESAMPLE": None,
    "TABLE_CONSTRAINTS": None,
    "TABLE_OPTIONS": None,
    "TABLE_SNAPSHOTS": None,
    "TABLE_STORAGE_BY_ORGANIZATION": None,
    "TABLE_STORAGE_BY_PROJECT": None,
    "TABLE_STORAGE_USAGE_TIMELINE": None,
    "TABLE_STORAGE_USAGE_TIMELINE_BY_ORGANIZATION": None,
    "TAN": None,
    "TANH": None,
    "THEN": None,
    "TIME": None,
    "TIME_ADD": None,
    "TIME_DIFF": None,
    "TIME_SUB": None,
    "TIME_TRUNC": None,
    "TO": None,
    "TO_BASE32": None,
    "TO_BASE64": None,
    "TO_CODE_POINTS": None,
    "TO_HEX": None,
    "TO_JSON": None,
    "TO_JSON_STRING": None,
    "TRANSLATE": None,
    "TREAT": None,
    "TRIM": None,
    "TRUE": None,
    "TRUNC": None,
    "UNBOUNDED": None,
    "UNICODE": None,
    "UNION": None,
    "UNIX_DATE": None,
    "UNNEST": None,
    "UPDATE": None,
    "UPPER": None,
    "USING": None,
    "VALUES": None,
    "VARIANCE": None,
    "VAR_POP": None,
    "VAR_SAMP": None,
    "VECTOR_INDEXES": None,
    "VECTOR_INDEX_COLUMNS": None,
    "VECTOR_INDEX_OPTIONS": None,
    "VIEW": None,
    "VIEW SET OPTIONS": None,
    "WHEN": None,
    "WHEN ERROR": None,
    "WHERE": None,
    "WHILE": None,
    "WINDOW": None,
    "WITH": None,
    "WITHIN": None,
    "__TABLES__": None,
}

KEYWORD_META: dict[str, str] = {
    "ABS": "Computes the absolute value of X.",
    "ACOS": "Computes the inverse cosine of X.",
    "ACOSH": "Computes the inverse hyperbolic cosine of X.",
    "ANY_VALUE": "Gets an expression for some row.",
    "APPROX_COUNT_DISTINCT": "Gets the approximate result for COUNT(DISTINCT expression).",
    "APPROX_QUANTILES": "Gets the approximate quantile boundaries.",
    "APPROX_TOP_COUNT": "Gets the approximate top elements and their approximate count.",
    "APPROX_TOP_SUM": "Gets the approximate top elements and sum, based on the approximate sum of an assigned weight.",
    "ARRAY": "Produces an array with one element for each row in a subquery.",
    "ARRAY_AGG": "Gets an array of values.",
    "ARRAY_CONCAT": "Concatenates one or more arrays with the same element type into a single array.",
    "ARRAY_CONCAT_AGG": "Concatenates arrays and returns a single array as a result.",
    "ARRAY_LENGTH": "Gets the number of elements in an array.",
    "ARRAY_REVERSE": "Reverses the order of elements in an array.",
    "ARRAY_TO_STRING": "Produces a concatenation of the elements in an array as a STRING value.",
    "ASCII": "Gets the ASCII code for the first character or byte in a STRING or BYTES value.",
    "ASIN": "Computes the inverse sine of X.",
    "ASINH": "Computes the inverse hyperbolic sine of X.",
    "ATAN": "Computes the inverse tangent of X.",
    "ATAN2": "Computes the inverse tangent of X/Y, using the signs of X and Y to determine the quadrant.",
    "ATANH": "Computes the inverse hyperbolic tangent of X.",
    "AVG": "Gets the average of non-NULL values.",
    "BIT_AND": "Performs a bitwise AND operation on an expression.",
    "BIT_COUNT": "Gets the number of bits that are set in an input expression.",
    "BIT_OR": "Performs a bitwise OR operation on an expression.",
    "BIT_XOR": "Performs a bitwise XOR operation on an expression.",
    "BOOL": "Converts a JSON boolean to a SQL BOOL value.",
    "BYTE_LENGTH": "Gets the number of BYTES in a STRING or BYTES value.",
    "CAST": "Convert the results of an expression to the given type.",
    "CBRT": "Computes the cube root of X.",
    "CEIL": "Gets the smallest integral value that is not less than X.",
    "CEILING": "Synonym of CEIL.",
    "CHARACTER_LENGTH": "Synonym for CHAR_LENGTH.",
    "CHAR_LENGTH": "Gets the number of characters in a STRING value.",
    "CHR": "Converts a Unicode code point to a character.",
    "CODE_POINTS_TO_BYTES": "Converts an array of extended ASCII code points to a BYTES value.",
    "CODE_POINTS_TO_STRING": "Converts an array of extended ASCII code points to a STRING value.",
    "COLLATE": "Combines a STRING value and a collation specification into a collation specification-supported STRING value.",
    "CONCAT": "Concatenates one or more STRING or BYTES values into a single result.",
    "CONTAINS_SUBSTR": "Performs a normalized, case-insensitive search to see if a value exists as a substring in an expression.",
    "CORR": "Computes the Pearson coefficient of correlation of a set of number pairs.",
    "COS": "Computes the cosine of X.",
    "COSH": "Computes the hyperbolic cosine of X.",
    "COSINE_DISTANCE": "Computes the cosine distance between two vectors.",
    "COT": "Computes the cotangent of X.",
    "COTH": "Computes the hyperbolic cotangent of X.",
    "COUNT": "Gets the number of rows in the input, or the number of rows with an expression evaluated to any value other than NULL.",
    "COUNTIF": "Gets the count of TRUE values for an expression.",
    "COVAR_POP": "Computes the population covariance of a set of number pairs.",
    "COVAR_SAMP": "Computes the sample covariance of a set of number pairs.",
    "CSC": "Computes the cosecant of X.",
    "CSCH": "Computes the hyperbolic cosecant of X.",
    "CUME_DIST": "Gets the cumulative distribution (relative position (0,1]) of each row within a window.",
    "CURRENT_DATE": "Returns the current date as a DATE value.",
    "CURRENT_DATETIME": "Returns the current date and time as a DATETIME value.",
    "CURRENT_TIME": "Returns the current time as a TIME value.",
    "DATE": "Constructs a DATE value.",
    "DATETIME": "Constructs a DATETIME value.",
    "DATETIME_ADD": "Adds a specified time interval to a DATETIME value.",
    "DATETIME_DIFF": "Gets the number of intervals between two DATETIME values.",
    "DATETIME_SUB": "Subtracts a specified time interval from a DATETIME value.",
    "DATETIME_TRUNC": "Truncates a DATETIME value.",
    "DATE_ADD": "Adds a specified time interval to a DATE value.",
    "DATE_DIFF": "Gets the number of intervals between two DATE values.",
    "DATE_FROM_UNIX_DATE": "Interprets an INT64 expression as the number of days since 1970-01-01.",
    "DATE_SUB": "Subtracts a specified time interval from a DATE value.",
    "DATE_TRUNC": "Truncates a DATE value.",
    "DENSE_RANK": "Gets the dense rank (1-based, no gaps) of each row within a window.",
    "DIV": "Divides integer X by integer Y.",
    "EDIT_DISTANCE": "Computes the Levenshtein distance between two STRING or BYTES values.",
    "ENDS_WITH": "Checks if a STRING or BYTES value is the suffix of another value.",
    "ERROR": "Produces an error with a custom error message.",
    "EUCLIDEAN_DISTANCE": "Computes the Euclidean distance between two vectors.",
    "EXP": "Computes e to the power of X.",
    "EXTRACT": "Extracts part of an INTERVAL value.",
    "FARM_FINGERPRINT": "Computes the fingerprint of a STRING or BYTES value, using the FarmHash Fingerprint64 algorithm.",
    "FIRST_VALUE": "Gets a value for the first row in the current window frame.",
    "FLOAT64": "Converts a JSON number to a SQL FLOAT64 value.",
    "FLOOR": "Gets the largest integral value that is not greater than X.",
    "FORMAT": "Formats data and produces the results as a STRING value.",
    "FORMAT_DATE": "Formats a DATE value according to a specified format string.",
    "FORMAT_DATETIME": "Formats a DATETIME value according to a specified format string.",
    "FORMAT_TIME": "Formats a TIME value according to the specified format string.",
    "FROM_BASE32": "Converts a base32-encoded STRING value into a BYTES value.",
    "FROM_BASE64": "Converts a base64-encoded STRING value into a BYTES value.",
    "FROM_HEX": "Converts a hexadecimal-encoded STRING value into a BYTES value.",
    "GENERATE_ARRAY": "Generates an array of values in a range.",
    "GENERATE_DATE_ARRAY": "Generates an array of dates in a range.",
    "GENERATE_TIMESTAMP_ARRAY": "Generates an array of timestamps in a range.",
    "GREATEST": "Gets the greatest value among X1,...,XN.",
    "GROUPING": "Checks if a groupable value in the GROUP BY clause is aggregated.",
    "IEEE_DIVIDE": "Divides X by Y, but does not generate errors for division by zero or overflow.",
    "INITCAP": "Formats a STRING as proper case, which means that the first character in each word is uppercase and all other characters are lowercase.",
    "INSTR": "Finds the position of a subvalue inside another value, optionally starting the search at a given offset or occurrence.",
    "INT64": "Converts a JSON number to a SQL INT64 value.",
    "IS_INF": "Checks if X is positive or negative infinity.",
    "IS_NAN": "Checks if X is a NaN value.",
    "JSON_ARRAY": "Creates a JSON array.",
    "JSON_ARRAY_APPEND": "Appends JSON data to the end of a JSON array.",
    "JSON_ARRAY_INSERT": "Inserts JSON data into a JSON array.",
    "JSON_EXTRACT": "(Deprecated) Extracts a JSON value and converts it to a SQL JSON-formatted STRING or JSON value.",
    "JSON_EXTRACT_ARRAY": "(Deprecated) Extracts a JSON array and converts it to a SQL ARRAY<JSON-formatted STRING> or ARRAY<JSON> value.",
    "JSON_EXTRACT_SCALAR": "(Deprecated) Extracts a JSON scalar value and converts it to a SQL STRING value.",
    "JSON_EXTRACT_STRING_ARRAY": "(Deprecated) Extracts a JSON array of scalar values and converts it to a SQL ARRAY<STRING> value.",
    "JSON_OBJECT": "Creates a JSON object.",
    "JSON_QUERY": "Extracts a JSON value and converts it to a SQL JSON-formatted STRING or JSON value.",
    "JSON_QUERY_ARRAY": "Extracts a JSON array and converts it to a SQL ARRAY<JSON-formatted STRING> or ARRAY<JSON> value.",
    "JSON_REMOVE": "Produces JSON with the specified JSON data removed.",
    "JSON_SET": "Inserts or replaces JSON data.",
    "JSON_STRIP_NULLS": "Removes JSON nulls from JSON objects and JSON arrays.",
    "JSON_TYPE": "Gets the JSON type of the outermost JSON value and converts the name of this type to a SQL STRING value.",
    "JSON_VALUE": "Extracts a JSON scalar value and converts it to a SQL STRING value.",
    "JSON_VALUE_ARRAY": "Extracts a JSON array of scalar values and converts it to a SQL ARRAY<STRING> value.",
    "JUSTIFY_DAYS": "Normalizes the day part of an INTERVAL value.",
    "JUSTIFY_HOURS": "Normalizes the time part of an INTERVAL value.",
    "JUSTIFY_INTERVAL": "Normalizes the day and time parts of an INTERVAL value.",
    "LAG": "Gets a value for a preceding row.",
    "LAST_DAY": "Gets the last day in a specified time period that contains a DATETIME value.",
    "LAST_VALUE": "Gets a value for the last row in the current window frame.",
    "LAX_BOOL": "Attempts to convert a JSON value to a SQL BOOL value.",
    "LAX_FLOAT64": "Attempts to convert a JSON value to a SQL FLOAT64 value.",
    "LAX_INT64": "Attempts to convert a JSON value to a SQL INT64 value.",
    "LAX_STRING": "Attempts to convert a JSON value to a SQL STRING value.",
    "LEAD": "Gets a value for a subsequent row.",
    "LEAST": "Gets the least value among X1,...,XN.",
    "LEFT": "Gets the specified leftmost portion from a STRING or BYTES value.",
    "LENGTH": "Gets the length of a STRING or BYTES value.",
    "LN": "Computes the natural logarithm of X.",
    "LOG": "Computes the natural logarithm of X or the logarithm of X to base Y.",
    "LOG10": "Computes the natural logarithm of X to base 10.",
    "LOGICAL_AND": "Gets the logical AND of all non-NULL expressions.",
    "LOGICAL_OR": "Gets the logical OR of all non-NULL expressions.",
    "LOWER": "Formats alphabetic characters in a STRING value as lowercase. Formats ASCII characters in a BYTES value as lowercase.",
    "LPAD": "Prepends a STRING or BYTES value with a pattern.",
    "LTRIM": "Identical to the TRIM function, but only removes leading characters.",
    "MAKE_INTERVAL": "Constructs an INTERVAL value.",
    "MAX": "Gets the maximum non-NULL value.",
    "MAX_BY": "Synonym for ANY_VALUE(x HAVING MAX y).",
    "MD5": "Computes the hash of a STRING or BYTES value, using the MD5 algorithm.",
    "MIN": "Gets the minimum non-NULL value.",
    "MIN_BY": "Synonym for ANY_VALUE(x HAVING MIN y).",
    "MOD": "Gets the remainder of the division of X by Y.",
    "NORMALIZE": "Case-sensitively normalizes the characters in a STRING value.",
    "NORMALIZE_AND_CASEFOLD": "Case-insensitively normalizes the characters in a STRING value.",
    "NTH_VALUE": "Gets a value for the Nth row of the current window frame.",
    "NTILE": "Gets the quantile bucket number (1-based) of each row within a window.",
    "OCTET_LENGTH": "Alias for BYTE_LENGTH.",
    "PARSE_BIGNUMERIC": "Converts a STRING value to a BIGNUMERIC value.",
    "PARSE_DATE": "Converts a STRING value to a DATE value.",
    "PARSE_DATETIME": "Converts a STRING value to a DATETIME value.",
    "PARSE_JSON": "Converts a JSON-formatted STRING value to a JSON value.",
    "PARSE_NUMERIC": "Converts a STRING value to a NUMERIC value.",
    "PARSE_TIME": "Converts a STRING value to a TIME value.",
    "PERCENTILE_CONT": "Computes the specified percentile for a value, using linear interpolation.",
    "PERCENTILE_DISC": "Computes the specified percentile for a discrete value.",
    "PERCENT_RANK": "Gets the percentile rank (from 0 to 1) of each row within a window.",
    "POW": "Produces the value of X raised to the power of Y.",
    "POWER": "Synonym of POW.",
    "RAND": "Generates a pseudo-random value of type FLOAT64 in the range of [0, 1).",
    "RANGE_BUCKET": "Scans through a sorted array and returns the 0-based position of a point's upper bound.",
    "RANK": "Gets the rank (1-based) of each row within a window.",
    "REGEXP_CONTAINS": "Checks if a value is a partial match for a regular expression.",
    "REGEXP_EXTRACT": "Produces a substring that matches a regular expression.",
    "REGEXP_EXTRACT_ALL": "Produces an array of all substrings that match a regular expression.",
    "REGEXP_INSTR": "Finds the position of a regular expression match in a value, optionally starting the search at a given offset or occurrence.",
    "REGEXP_REPLACE": "Produces a STRING value where all substrings that match a regular expression are replaced with a specified value.",
    "REGEXP_SUBSTR": "Synonym for REGEXP_EXTRACT.",
    "REPEAT": "Produces a STRING or BYTES value that consists of an original value, repeated.",
    "REPLACE": "Replaces all occurrences of a pattern with another pattern in a STRING or BYTES value.",
    "REVERSE": "Reverses a STRING or BYTES value.",
    "RIGHT": "Gets the specified rightmost portion from a STRING or BYTES value.",
    "ROUND": "Rounds X to the nearest integer or rounds X to N decimal places after the decimal point.",
    "ROW_NUMBER": "Gets the sequential row number (1-based) of each row within a window.",
    "RPAD": "Appends a STRING or BYTES value with a pattern.",
    "RTRIM": "Identical to the TRIM function, but only removes trailing characters.",
    "SAFE_ADD": "Equivalent to the addition operator (X + Y), but returns NULL if overflow occurs.",
    "SAFE_CAST": "Similar to the CAST function, but returns NULL when a runtime error is produced.",
    "SAFE_CONVERT_BYTES_TO_STRING": "Converts a BYTES value to a STRING value and replace any invalid UTF-8 characters with the Unicode replacement character, U+FFFD.",
    "SAFE_DIVIDE": "Equivalent to the division operator (X / Y), but returns NULL if an error occurs.",
    "SAFE_MULTIPLY": "Equivalent to the multiplication operator (X * Y), but returns NULL if overflow occurs.",
    "SAFE_NEGATE": "Equivalent to the unary minus operator (-X), but returns NULL if overflow occurs.",
    "SAFE_SUBTRACT": "Equivalent to the subtraction operator (X - Y), but returns NULL if overflow occurs.",
    "SEC": "Computes the secant of X.",
    "SECH": "Computes the hyperbolic secant of X.",
    "SELECT": "Defines the columns that the query will return. Expressions can refer to columns in any of the from_items in its corresponding FROM clause.",
    "SHA1": "Computes the hash of a STRING or BYTES value, using the SHA-1 algorithm.",
    "SHA256": "Computes the hash of a STRING or BYTES value, using the SHA-256 algorithm.",
    "SHA512": "Computes the hash of a STRING or BYTES value, using the SHA-512 algorithm.",
    "SIGN": "Produces -1 , 0, or +1 for negative, zero, and positive arguments respectively.",
    "SIN": "Computes the sine of X.",
    "SINH": "Computes the hyperbolic sine of X.",
    "SOUNDEX": "Gets the Soundex codes for words in a STRING value.",
    "SPLIT": "Splits a STRING or BYTES value, using a delimiter.",
    "SQRT": "Computes the square root of X.",
    "STARTS_WITH": "Checks if a STRING or BYTES value is a prefix of another value.",
    "STDDEV": "An alias of the STDDEV_SAMP function.",
    "STDDEV_POP": "Computes the population (biased) standard deviation of the values.",
    "STDDEV_SAMP": "Computes the sample (unbiased) standard deviation of the values.",
    "STRING": "Converts a JSON string to a SQL STRING value.",
    "STRING_AGG": "Concatenates non-NULL STRING or BYTES values.",
    "STRPOS": "Finds the position of the first occurrence of a subvalue inside another value.",
    "SUBSTR": "Gets a portion of a STRING or BYTES value.",
    "SUBSTRING": "Alias for SUBSTR",
    "SUM": "Gets the sum of non-NULL values.",
    "TAN": "Computes the tangent of X.",
    "TANH": "Computes the hyperbolic tangent of X.",
    "TIME": "Constructs a TIME value.",
    "TIME_ADD": "Adds a specified time interval to a TIME value.",
    "TIME_DIFF": "Gets the number of intervals between two TIME values.",
    "TIME_SUB": "Subtracts a specified time interval from a TIME value.",
    "TIME_TRUNC": "Truncates a TIME value.",
    "TO_BASE32": "Converts a BYTES value to a base32-encoded STRING value.",
    "TO_BASE64": "Converts a BYTES value to a base64-encoded STRING value.",
    "TO_CODE_POINTS": "Converts a STRING or BYTES value into an array of extended ASCII code points.",
    "TO_HEX": "Converts a BYTES value to a hexadecimal STRING value.",
    "TO_JSON": "Converts a SQL value to a JSON value.",
    "TO_JSON_STRING": "Converts a SQL value to a JSON-formatted STRING value.",
    "TRANSLATE": "Within a value, replaces each source character with the corresponding target character.",
    "TRIM": "Removes the specified leading and trailing Unicode code points or bytes from a STRING or BYTES value.",
    "TRUNC": "Rounds a number like ROUND(X) or ROUND(X, N), but always rounds towards zero and never overflows.",
    "UNICODE": "Gets the Unicode code point for the first character in a value.",
    "UNIX_DATE": "Converts a DATE value to the number of days since 1970-01-01.",
    "UPPER": "Formats alphabetic characters in a STRING value as uppercase. Formats ASCII characters in a BYTES value as uppercase.",
    "VARIANCE": "An alias of VAR_SAMP.",
    "VAR_POP": "Computes the population (biased) variance of the values.",
    "VAR_SAMP": "Computes the sample (unbiased) variance of the values.",
}
