CREATE OR REPLACE FUNCTION
  ${DATASET.NAME}.current_datetime()
RETURNS DATETIME AS (
    DATETIME_TRUNC(EXTRACT(DATETIME FROM ${DATASET.NAME}.current_timestamp() AT TIME ZONE "${TIMEZONE}"), SECOND)
  );
