[style]
color = "#f0f0ff"
bold = false

[theme.styles]
attr = "bold #fafa19"
notice = "#32ccfe"
code = "bold #f08375"
"code.command" = "bold #3465a4"
"code.keybind" = "bold not dim #ff00ff"
"code.lflag" = "bold #00ffff"
"code.sflag" = "bold #00ff00"
args = "bold #34e2e2"
"header.str" = "#ff0000"
"header.dt" = "#ffff00"
"header.bool" = "#ff0000"
"header.num" = "#00ffff"
failure = "#f0f0ff on #ff0000"
none = "#f0f0ff"
prompt = "#f0f0ff"
dimmed = "#888888"
saved = "#00ff00"
"tree.line" = "bold magenta"
"active.entry" = "bold italic"
"iso8601.date" = "#3465a4"
"iso8601.time" = "#7f007f"
"table.header" = "bold #f0f0ff"
"table.footer" = "dim italic"
"table.cell" = "#f0f0ff"
"table.cell.empty" = "italic #888888"
"table.title" = "bold #f0f0ff"
"table.caption" = "dim italic"
"status.message" = "#19667f"
"status.spinner" = "#32ccfe"
"progress.description" = "#f0f0ff"
"progress.spinner" = "#32ccfe"
"repr.tag_contents" = "bold"
"repr.attrib_equal" = "bold red"
"repr.attrib_name" = "not dim #ffff00"
"repr.attrib_value" = "not dim #ff00ff"
"repr.number" = '#00ffff'
"repr.number_complex" = '#00ffff'
"repr.str" = "#00a500"
"scope.key.special" = "italic dim #ffff00"
"scope.key" = "not dim italic #ffff00"
"scope.equals" = "bold #ff0000"
"scope.border" = "#0000ff"
"log.time" = "dim #78787f"
"log.message" = "#f0f0ff"
"log.main" = "#f0f0ff"
"log.build" = "dim #fafa19"
"log.validate" = "dim #8205b4"
"log.error" = "#ff0000"
"log.path" = "dim #d2d2e6"
